ERPDIFF_EXPERIMENT_SPEC:
  dataset: dataset2
  table2_hyperparams:
    finetune:
      batch_size: 64
      initial_lr: 0.002
      weight_decay: 0.0005
  loss:
    focal:
      alpha: 0.80
      gamma: 2.0
